version: '3.7'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '64048:5432'
volumes:
  postgres:
